kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-hdd
  namespace: mailu-mailserver
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-client-nfs-client-provisioner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mail-storage
  namespace: mailu-mailserver
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-client-nfs-client-provisioner
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-client
